version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      # Volume para cache do Cypress
      - cypress-cache:/root/.cache/Cypress
    environment:
      - DISPLAY=:0
    # Configuração para rodar Cypress em modo headless se necessário
    shm_size: "2g"

volumes:
  cypress-cache: